theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: planetonstage.org
  summary:
    position: hero
  breadcrumb:
    position: hero-end
  i18n:
    positions:
      - footer